//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDataModelDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeInfo
    {
        public int eid { get; set; }
        public string ename { get; set; }
        public string edesignation { get; set; }
        public Nullable<long> esalary { get; set; }
    }
}
